---
abstract: 'A URI-like object with Path::Abstract capabilities'
author:
  - 'Robert Krimen, C<< <rkrimen at cpan.org> >>'
build_requires:
  Test::More: 0
  Test::Most: 0
distribution_type: module
generated_by: 'Module::Install version 0.750'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: URI-PathAbstract
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Path::Abstract: 0.089
  Scalar::Util: 0
  URI: 0
version: 0.01
